### ISSUE TITLE
Gets deployed but not shown in keycloak

### ISSUE THREAD

**Issue by timololipop** [micedre/keycloak-mail-whitelisting#43]
Hey!

I got the following issue: KeyCloak deploys it just fine (v16) according to the logs. I also restarted it but I cant find it in the Provider Drop Down Menu,

![image](https://user-images.githubusercontent.com/25285295/156824456-c671654c-571e-4950-a9fc-3dc60187fab8.png)

Am I missing something?

Thank you.

**Comment by micedre** [comment]
You need to add an execution on the registration flow : 

* First Copy the existing registratuion workflow 

![image](https://user-images.githubusercontent.com/243027/157017455-e3aff7d1-a7ca-4fe4-a9b9-8fc75f429482.png)

* On this new auth flow, add an execution to the parent : 

![image](https://user-images.githubusercontent.com/243027/157017691-5ab81e66-0732-4621-836a-91be68defdc9.png)

* The new execution should appear : 

![image](https://user-images.githubusercontent.com/243027/157017838-e3a16778-d175-4292-bf43-fe5c8b75c2e8.png)

**Comment by timololipop** [comment]
Ah, okay! I didnt look there, thank you!
