### ISSUE TITLE
Allow whitelisting of whole email address not just the domain

### ISSUE THREAD

**Issue by crnakad** [micedre/keycloak-mail-whitelisting#45]
I would like to whitelist a specific email address, so that the user with this email can register and set the password all by him/herself.

**Comment by micedre** [comment]
Hi, did you try putting the complete mail adress in configuration ? It should work fine.

**Comment by crnakad** [comment]
when I enter the full email address i'm getting invalid email address during registration.
Adding a domain name only works

**Comment by crnakad** [comment]
![image](https://user-images.githubusercontent.com/86119195/158762273-e6381a48-fa6c-4ffd-9066-355c1092d6f4.png)
![image](https://user-images.githubusercontent.com/86119195/158762518-37c4623d-724c-44d3-9da1-a2f067dc497f.png)

**Comment by micedre** [comment]
Hi, thanks for the report, the new 1.4 version should handle this correctly : 

https://s01.oss.sonatype.org/service/local/repositories/releases/content/net/micedre/keycloak/keycloak-mail-whitelisting/1.4/keycloak-mail-whitelisting-1.4.jar

(the release should be in maven central soon)

**Comment by crnakad** [comment]
sorry for the late reply, this works!
thank you
