### ISSUE TITLE
Unexpected error in handling authentication

### ISSUE THREAD

**Issue by mariantanase** [micedre/keycloak-mail-whitelisting#50]
Hi,
Thanks for your plugin.
I need a little help if possible. I am using a standalone server **keycloak-15.0.2**. 
I've deployed the **keycloak-mail-whitelisting-1.3.3.jar**
On "_Profile Validation With Email Domain Check_" domain restrict configuration, I entered on "Valid domain for emails" field, the desidered domain in the following format: **mydomain.com**
No, when I try to register, this error message comes up:
"**Unexpected error in handling authentication request to identity provider**."

What I did wrong ?
Thanks

Server Version 	15.0.2
Java Version 	1.8.0_171

**Comment by mariantanase** [comment]
Nevermind, I noticed that it works with Keycloak 16.1.1

**Comment by micedre** [comment]
Hi,

> Nevermind, I noticed that it works with Keycloak 16.1.1

With the exact same configuration ? There should not be a difference between these 2 versions.  

Do you have a stack trace for the error ?

**Comment by mariantanase** [comment]
Yes, is the same configuration.
From **server.log**:
```
WARN  [org.keycloak.services] (default task-4) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: No user model provided for persisting changes
	at org.keycloak.userprofile.DefaultUserProfile.updateInternal(DefaultUserProfile.java:102)
	at org.keycloak.userprofile.DefaultUserProfile.update(DefaultUserProfile.java:97)
	at org.keycloak.userprofile.UserProfile.update(UserProfile.java:78)
	at org.keycloak.authentication.forms.RegistrationProfile.success(RegistrationProfile.java:96)
	at org.keycloak.authentication.FormAuthenticationFlow.processAction(FormAuthenticationFlow.java:252)
.........
```

**Comment by micedre** [comment]
Thank you, I will try to reproduce it. If you have any more information, do not hesitate to share it.
