### ISSUE TITLE
Keycloak 19.0.1 compatibility ?

### ISSUE THREAD

**Issue by mariantanase** [micedre/keycloak-mail-whitelisting#53]
Hi Cedric,

Is it possible to make this plugin compatible with the latest Keycloak release ? (19.0.1)

Thanks

**Comment by micedre** [comment]
Hello,

I'll start to look, but did you have an error?

**Comment by micedre** [comment]
There was an error, when configuring the valid domains, is that what you observed ?

I will release a new vzersion to fix it soon.

That said, the new user profile features offered by keycloak are able to validate mail without needing this extension, you should take a look

**Comment by mariantanase** [comment]
Thanks!
Can you provide the jar file also ?

**Comment by mariantanase** [comment]
Thanks !

**Comment by micedre** [comment]
Jar is here : https://repo1.maven.org/maven2/net/micedre/keycloak/keycloak-mail-whitelisting/1.5/keycloak-mail-whitelisting-1.5.jar

**Comment by mariantanase** [comment]
Yes, I noticed and I download it. Thank you!

I deployed the jar, I configured the domain list without error, but when validate it shows an error "Unexpected error in handling authentication". The configuration steps are different ?
But I don't know what you mean by "_validate mail without needing this extension_".

**Comment by mariantanase** [comment]
I resolved the issue with changing the steps order on registration copy flow.
![Screenshot 2022-08-09 at 10-22-27 Keycloak Administration Console](https://user-images.githubusercontent.com/3976174/183601491-e1463748-3653-4137-8017-a6532d571697.png)

The step "_Profile Validation with email domain check_" is important to be placed **BELOW**  "_Registration User Creation_".
