### ISSUE TITLE
"can't convert undefined to object"

### ISSUE THREAD

**Issue by RexSpex** [micedre/keycloak-mail-whitelisting#56]
Using:
Keycloak19.0.2
PostgresQL 14.2 (in RDS)

While the plugin appears to load, going to the config page appears to break it. see below. 

![image](https://user-images.githubusercontent.com/63176186/193600709-89f12b96-be1b-4cca-8994-08aaa77d1c0e.png)

![image](https://user-images.githubusercontent.com/63176186/193600371-a5eaac5a-b926-4d6a-ba59-6ce50b6ecb6d.png)

**Comment by AienTech** [comment]
Bump, also facing it with the same error.

**Comment by RexSpex** [comment]
Hey I figured it out. Go to the realm settings, themes, and change the admin console theme to "keycloak". it will resolve the issue.

**Comment by RexSpex** [comment]
![image](https://user-images.githubusercontent.com/63176186/197238764-ae3d7ee0-314f-449a-b3bb-666fa84adf23.png)

**Comment by RexSpex** [comment]
You can actually replicate the issue on an instance that doesn't even have the plugin. Just go to edit any of the settings in any Auth flow
