### ISSUE TITLE
Cannot add multiple domains

### ISSUE THREAD

**Issue by emmarichardson** [micedre/keycloak-mail-whitelisting#58]
I am sure I am doing this wrong - I have tried the following per the ?

domain1.com##domain2.com
domain1.com'##'domain2.com
'domain1.com''domain2.com'

What am I doing wrong?

Could not save the execution config: Unrecognized field "validDomains" (class org.keycloak.representations.idm.AuthenticatorConfigRepresentation), not marked as ignorable (3 known properties: "alias", "config", "id"]) at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 18] (through reference chain: org.keycloak.representations.idm.AuthenticatorConfigRepresentation["validDomains"])

**Comment by micedre** [comment]
Could you try with the last version ? It works for me

**Comment by emmarichardson** [comment]
I got it working - forget what I had to do...
