### ISSUE TITLE
It shows internal server error in keycloak v21.0.1

### ISSUE THREAD

**Issue by manishedulab** [micedre/keycloak-mail-whitelisting#60]
Hello ,
whenever I click on register button it shows me internal server error,
I'm using the 1.3.3 jar file , 
and one more thing I don't understand the step 7 of how to use so I have not performed it

**Comment by santicastro** [comment]
`docker-keycloak-1  | 2023-06-16 12:04:18,952 WARN  [org.keycloak.services] (executor-thread-0) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: No user model provided for persisting changes
docker-keycloak-1  |    at org.keycloak.userprofile.DefaultUserProfile.updateInternal(DefaultUserProfile.java:103)
docker-keycloak-1  |    at org.keycloak.userprofile.DefaultUserProfile.update(DefaultUserProfile.java:98)
docker-keycloak-1  |    at org.keycloak.userprofile.UserProfile.update(UserProfile.java:78)
docker-keycloak-1  |    at org.keycloak.authentication.forms.RegistrationProfile.success(RegistrationProfile.java:96)
docker-keycloak-1  |    at org.keycloak.authentication.FormAuthenticationFlow.processAction(FormAuthenticationFlow.java:252)
docker-keycloak-1  |    at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:134)
docker-keycloak-1  |    at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:977)
docker-keycloak-1  |    at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:311)
docker-keycloak-1  |    at org.keycloak.services.resources.LoginActionsService.processRegistration(LoginActionsService.java:655)
docker-keycloak-1  |    at org.keycloak.services.resources.LoginActionsService.registerRequest(LoginActionsService.java:711)
docker-keycloak-1  |    at org.keycloak.services.resources.LoginActionsService.processRegister(LoginActionsService.java:689)
docker-keycloak-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
docker-keycloak-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
docker-keycloak-1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docker-keycloak-1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
docker-keycloak-1  |    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
docker-keycloak-1  |    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
docker-keycloak-1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
docker-keycloak-1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
docker-keycloak-1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
docker-keycloak-1  |    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
docker-keycloak-1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
docker-keycloak-1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
docker-keycloak-1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
docker-keycloak-1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
docker-keycloak-1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
docker-keycloak-1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
docker-keycloak-1  |    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
docker-keycloak-1  |    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
docker-keycloak-1  |    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
docker-keycloak-1  |    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
docker-keycloak-1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
docker-keycloak-1  |    at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
docker-keycloak-1  |    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
docker-keycloak-1  |    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
docker-keycloak-1  |    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
docker-keycloak-1  |    at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
docker-keycloak-1  |    at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
docker-keycloak-1  |    at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
docker-keycloak-1  |    at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
docker-keycloak-1  |    at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
docker-keycloak-1  |    at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
docker-keycloak-1  |    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
docker-keycloak-1  |    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
docker-keycloak-1  |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
docker-keycloak-1  |    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
docker-keycloak-1  |    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
docker-keycloak-1  |    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
docker-keycloak-1  |    at java.base/java.lang.Thread.run(Thread.java:829)
`
