### ISSUE TITLE
Keycloak 22.X compatibility

### ISSUE THREAD

**Issue by bardyguillaume** [micedre/keycloak-mail-whitelisting#65]
Hi,
I'm using this plugin with Keycloak 22 and it is not working

I already made a pull request for keycloak 21 (easy) but for keycloak 22 there are breaking changes (jdk17) and javax -> jakarta.

**Comment by bardyguillaume** [comment]
#66 here is the pull request if needed

**Comment by micedre** [comment]
Thanks, fixed by #67
