### ISSUE TITLE
[docs] Do instructions in readme work on Keycloak 23?

### ISSUE THREAD

**Issue by danielloader** [micedre/keycloak-mail-whitelisting#80]
I'm trying to follow the readme instructions for enabling a flow step and I can't find any of the additional steps this provider should have added?

I've probably missed something but anything would be helpful here.

**Comment by AdoniasAlcantara** [comment]
The provider seems to be registered, but I don't know what to do afterwards.

![image](https://github.com/micedre/keycloak-mail-whitelisting/assets/13831456/6361ca76-7fcf-44ec-92fa-045d7d81c892)

**Comment by AdoniasAlcantara** [comment]
I was struggling to figure out how to add the provider action to the form validation in Keycloak 23, but now I noticed that there is a "+" button inside the flow, so now I can make use of the provider.

![image](https://github.com/micedre/keycloak-mail-whitelisting/assets/13831456/8fd4e754-8c76-4e54-94f0-0d318bd4a709)
